# Generated by Django 5.0.3 on 2024-04-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image_file',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
